name: Recovery Builder

on:
  workflow_dispatch:
    inputs:
      SELECT_RECOVERY:
        description: 'Please choose the custom recovery you want to build'
        required: true
        default: PBRP(Android-12.1)
        type: choice
        options:
          - PBRP(Android-12.1)
          - TWRP(twrp-12.1)
      SELECT_BRAND:
        description: 'Select your device brand'
        required: true
        default: xiaomi
        type: choice
        options:
            - xiaomi
      BUILD_VARIANT:
        description: 'Select Your Build Variant'
        required: true
        default: bootimage
        type: choice
        options:
            - bootimage
            - recovery
            - vendor_boot
            - pbrp
jobs:
  build:
    name: "Building Recovery: ${{ inputs.SELECT_RECOVERY }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "Building Recovery: ${{ inputs.SELECT_RECOVERY }}"
          echo "Brands: ${{ inputs.SELECT_BRAND }}"
          echo "Build Variant: ${{ inputs.BUILD_VARIANT }}"

