name: Recovery Builder

on:
  workflow_dispatch:
    inputs:
      SELECT_RECOVERY:
        description: 'Please choose the custom recovery you want to build'
        required: true
        default: PBRP(Android-12.1)
        type: choice
        options:
          - PBRP(Android-12.1)
          - TWRP(twrp-12.1)

jobs:
  build:
    name: "Building Recovery"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          e