name: Recovery Builder

on:
  workflow_dispatch:
    inputs:
      SELECT_RECOVERY:
        description: 'Please choose the custom recovery you want to build'
        required: true
        default: PBRP(Android-12.1)
        type: choice
        options:
          - PBRP(Android-12.1)
          - TWRP(twrp-12.1)
      SELECT_BRAND:
        description: 'Select your device brand'
        required: true
        default: xiaomi
        type: choice
        options:
            - xiaomi
      BUILD_VARIANT:
        description: 'Select Your Build Variant'
        required: true
        default: bootimage
        type: choice
        options:
            - bootimage
            - recoveryimage
            - vendorbootimage
            - pbrp
      CODENAME:
        description: 'Insert Your device codename'
        required: true
      DT_RECOVERY_URL:
        description: "Insert Your Device Tree URL In Here"
      DT_RECOVERY_BRANCH:
        description: "Insert Your Device Tree Branch In Here"
        required: true
      MAKEFILE_DT:
        description: "Specify Your Device Tree Makefile(example: twrp_codename)But You No Need Insert Again _codename"
        required: true
      CCACHE_SIZE_INPUT:
        description: "Enter Size CCACHE Your Wants"
        required: true
jobs:
  build:
    name: "Building: ${{ inputs.SELECT_RECOVERY }}"
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SELECTED_RECOVERY: ${{ inputs.SELECT_RECOVERY }}
        DEVICE_BRAND: ${{ inputs.SELECT_BRAND }}
        DEVICE_CODENAME: ${{ inputs.CODENAME }}
        BUILD_VAR: ${{ inputs.BUILD_VARIANT }}
        DT_LINK: ${{ inputs.DT_RECOVERY_URL }}
        DT_BRANCH: ${{ inputs.DT_RECOVERY_BRANCH }}
        PBRP_ANDROID_12_URL: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-12.1"
        TWRP_TWRP_12_URL: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1"
        CCACHE_DIR: ~/.ccache
        CCACHE_MAXSIZE: ${{ inputs.CCACHE_SIZE_INPUT }}G
    permissions:
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display All Information
        run: |
          echo "Building Recovery: ${{ env.SELECTED_RECOVERY }}"
          echo "Brands: ${{ env.DEVICE_BRAND }}"
          echo "Build Variant: ${{ env.BUILD_VAR }}"
          echo "Device Tree URL: ${{ env.DT_LINK }}"
          echo "Device Tree Branch: ${{ env.DT_BRANCH }}"
          
      - name: Cleanup Disk
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set Swap To 4GB
        uses: pierotofy/set-swap-space@master
        with:
            swap-size-gb: 4

      - name: Setting ccache
        uses: actions/cache@v3
        with:
            path: ~/.ccache
            key: ${{ runner.os }}-ccache-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-ccache

      - name: Apply CCACHE
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          
      - name: Display System Information
        run: |
          echo "OS: $(lsb_release -a 2>/dev/null | awk '/Description/ {print $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13}')"
          echo "Users $(whoami)"
          echo "Kernel Version: $(uname -r)"
          echo "CPU: $(lscpu | grep 'Model name' | awk -F: '{print $2}' | xargs)"
          echo "CPU Cores: $(nproc) Cores"
          echo "Total Memory Size: $(free -h | awk '/^Mem:/ {print $4}')"
          echo "Total Swap Size: $(free -h | awk '/^Swap:/ {print $2}')"
          echo "Total Free Disk: $(df -h $(pwd) | awk 'NR==2 {print $4}')"

      - name: Install Depencies Needed
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt install -y python3 python2 python3 bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo

      - name: Sync Recovery
        run: |
          mkdir -p buildir
          cd buildir

          # Condition PBRP
          if [[ "${{ env.SELECTED_RECOVERY }}" == *"PBRP(Android-12.1)"* ]]; then
          repo init -u ${{ env.PBRP_ANDROID_12_URL }}
          repo sync --force-sync --no-clone-bundle -j$(nproc)
          git clone ${{ inputs.DT_RECOVERY_URL }} -b ${{ inputs.DT_RECOVERY_BRANCH }} device/${{ env.DEVICE_BRAND }}/${{ env.DEVICE_CODENAME}}
          source build/envsetup.sh
          cd buildir
          lunch ${{ inputs.MAKEFILE_DT }}_${{ env.DEVICE_CODENAME }}-eng
          mka ${{ env.BUILD_VAR }} -j$(nproc)

          # Condition TWRP
          elif [[ "${{ env.SELECTED_RECOVERY }}" == *"TWRP(twrp-12.1)"* ]]; then
          repo init -u ${{ env.TWRP_TWRP_12_URL }}
          repo sync --force-sync --no-clone-bundle -j$(nproc)
          git clone ${{ inputs.DT_RECOVERY_URL }} -b ${{ inputs.DT_RECOVERY_BRANCH }} device/${{ env.DEVICE_BRAND }}/${{ env.DEVICE_CODENAME}}
          source build/envsetup.sh
          cd buildir
          lunch ${{ inputs.MAKEFILE_DT }}_${{ env.DEVICE_CODENAME }}-eng
          mka ${{ env.BUILD_VAR }} -j$(nproc)
          fi

      - name: Uploading Into Releases
        uses: softprops/action-gh-release@master
        with:
            files: |
              buildir/out/target/product/${{ env.DEVICE_CODENAME}}/PBRP*.zip
              buildir/out/target/product/${{ env.DEVICE_CODENAME}}/boot.img
            name: "Result Build For Device: ${{ env.DEVICE_CODENAME}}"
            tag_name: ${{ github.run_id }}
            body: |
             Target Recovery: ${{ env.SELECTED_RECOVERY }}
             Device Tree: ${{ env.DT_LINK }}
             Device Branch: ${{ env.DT_BRANCH }}
             Device Codename: ${{ env.DEVICE_CODENAME }}
             Device Brands: ${{ env.DEVICE_BRAND }}
             Build Variant: ${{ env.BUILD_VAR }}
             Requested Build By: ${{ github.actor }}